astaguru/Astaguru/Models/AdminCms/Artist.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Astaguru.Models.AdminCms
{
    public class Artist
    {
        public string Sr { get; set; }

        public int artistid { get; set; }

        [Required(ErrorMessage = "Please enter First Name")]
        public string firstname { get; set; }

        [Required(ErrorMessage = "Please enter Last Name")]
        public string lastname { get; set; }

        [Required(ErrorMessage = "Please enter Profile Description")]
        public string Profile { get; set; }

        [Required(ErrorMessage = "Picture Required")]
        public string Picture { get; set; }

        public string imgPreview { get; set; }

        public List<Artist> GridList { get; set; }
    }
}

astaguru/Astaguru/Models/AdminCms/AuctionList.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Astaguru.Models.AdminCms
{
    public class AuctionList
    {
        public string Sr { get; set; }

        public int Auctionid { get; set; }

        [Required(ErrorMessage = "Please Enter Auction Name")]
        public string Auctionname { get; set; }

        public string auctiondate { get; set; }

        public string Date { get; set; }

        public decimal DollarRate { get; set; }

        [Required(ErrorMessage = "Image Required")]
        public string image { get; set; }

        public string status { get; set; }

        public int auctionType { get; set; }

        [Required(ErrorMessage = "Total Sale Value Rs Required")]
        public string totalSaleValueRs { get; set; }

        [Required(ErrorMessage = "Total Sale Value Us Required")]
        public string totalSaleValueUs { get; set; }

        [Required(ErrorMessage = "Auction Banner Required")]
        public string auctionBanner { get; set; }

        [Required(ErrorMessage = "Auction WebImage Required")]
        public string auctionWebImage { get; set; }

        //[Required(ErrorMessage = "Recent Auction Banner Required")]
        public string recentAuctionBanner { get; set; }

        public string imgPreview { get; set; }

        public string imgPreview1 { get; set; }
        public string imgPreview2 { get; set; }
        public string imgPreview3 { get; set; }


        public List<AuctionList> GridList { get; set; }


    }
}

astaguru/Astaguru/Models/AdminCms/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Astaguru.Models.AdminCms
{
    public class Category
    {
        public string Sr { get; set; }
        public int categoryid { get; set; }

        [Required(ErrorMessage = "Please enter Category")]
        public string category { get; set; }

        public List<Category> GridList { get; set; }
    }
}

astaguru/Astaguru/Models/AdminCms/CurrentVacancy.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Astaguru.Models.AdminCms
{
    public class CurrentVacancy
    {
        public string Sr { get; set; }
        public int Id { get; set; }

        [Required(ErrorMessage = "Job Title is Required ")]
        public string Job_Title { get; set; }


        [Required(ErrorMessage = "Business Unit is Required ")]
        public string Business_Unit { get; set; }

        [Required(ErrorMessage = "Job Responsibility is Required ")]
        public string Job_Responsibility { get; set; }

        [Required(ErrorMessage = "Responsibilities is Required ")]
        public string Responsibilities { get; set; }

        [Required(ErrorMessage = "Functional Skills is Required ")]
        public string Functional_Skills { get; set; }

        [Required(ErrorMessage = "Technical skills is Required ")]
        public string Technical_skills { get; set; }

        [Required(ErrorMessage = "Qualification is Required ")]
        public string Qualification { get; set; }

        [Required(ErrorMessage = "Salary is Required ")]
        public string Salary { get; set; }

        [Required(ErrorMessage = "Experience is Required ")]
        public string Experience { get; set; }

        public List<CurrentVacancy> GridList { get; set; }
    }
}

astaguru/Astaguru/Models/AdminCms/Faq.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Astaguru.Models.AdminCms
{
    public class Faq
    {
        public string Sr { get; set; }
        public int Id { get; set; }

        [Required(ErrorMessage = "Category is Required ")]
        public string Category { get; set; }

        [Required(ErrorMessage = "Title is Required ")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Description is Required ")]
        public string Description { get; set; }

       public List<Faq> GridList { get; set; }
    }
}

astaguru/Astaguru/Models/AdminCms/Medium.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Astaguru.Models.AdminCms
{
    public class Medium
    {
        public string Sr { get; set; }
        public int mediumid { get; set; }

        [Required(ErrorMessage = "Please enter Medium")]
        public string medium { get; set; }

        public List<Medium> GridList { get; set; }
    }
}

astaguru/Astaguru/Models/AdminCms/Style.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Astaguru.Models.AdminCms
{
    public class Style
    {
        public string Sr { get; set; }
        public int styleid { get; set; }

        [Required(ErrorMessage = "Please Enter Style")]
        public string style { get; set; }

        public List<Style> GridList { get; set; }

    }
}

astaguru/Astaguru/Controllers/AdminCmsController.cs
using Astaguru.Authentication;
using Astaguru.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using iTextSharp.text;
using iTextSharp.text.html.simpleparser;
using System.Web.UI;
using iTextSharp.text.pdf;
using System.Net.Mail;
using System.Net;
using System.Web.Script.Serialization;
using iTextSharp.tool.xml;
using Dapper;
using Astaguru.Services.UserService;
using Astaguru.Services;
using Astaguru.Models.AdminCms;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using System.Xml;

namespace Astaguru.Controllers
{
    [CustomAdminAccessFilter]
    public class AdminCmsController : Controller
    {
        // GET: AdminCms
        Utility util = new Utility();



        #region xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --- Admin Index --- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

        public ActionResult Index()
        {
            //var count = Counting();
            //ViewBag.CurrentOpening = count["CurrentOpening"].ToString();
            //ViewBag.ApplyForJob = count["ApplyForJob"].ToString();
            //ViewBag.ContactUs = count["ContactUs"].ToString();
            //ViewBag.RequestACallback = count["RequestACallback"].ToString();
            return View();
        }

        public Dictionary<string, string> Counting()
        {
            Dictionary<string, string> objDic = new Dictionary<string, string>();
            StringBuilder strbuil = new StringBuilder();
            DataSet ds = new DataSet();
            ds = util.Display1("Exec Proc_CMS 'adminIndexCount'");
            if (ds.Tables.Count > 0)
            {
                //CurrentOpening
                objDic.Add(ds.Tables[0].Rows[0]["Tbl"].ToString(), ds.Tables[0].Rows[0]["Count"].ToString());

                //ApplyForJob
                objDic.Add(ds.Tables[1].Rows[0]["Tbl"].ToString(), ds.Tables[1].Rows[0]["Count"].ToString());

                //ContactUs
                objDic.Add(ds.Tables[2].Rows[0]["Tbl"].ToString(), ds.Tables[2].Rows[0]["Count"].ToString());

                //RequestACallback
                objDic.Add(ds.Tables[3].Rows[0]["Tbl"].ToString(), ds.Tables[3].Rows[0]["Count"].ToString());
            }
            return objDic;
        }

        #endregion


        #region xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx--- Admin Profile Section Start---xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        public ActionResult UpdateProfile()
        {
            DataTable dt = GetAdminDataForProfileUpdate();
            Login log = new Login();

            log.Id = dt.Rows[0]["Id"].ToString();
            log.Name = dt.Rows[0]["Name"].ToString();
            log.Emailid = dt.Rows[0]["Emailid"].ToString();
            log.Mobileno = dt.Rows[0]["Mobileno"].ToString();
            return View(log);
        }

        public DataTable GetAdminDataForProfileUpdate()
        {
            DataTable dt = new DataTable();
            try
            {
                dt = util.Display("Execute Proc_SuperAdminLogin 'GETDETAIL_FOR_UPDATE'");
            }
            catch (Exception ex)
            {

                throw ex;
            }
            return dt;
        }

        [HttpPost]
        public JsonResult UpdateProfile(Login logobj)
        {
            var response = "";

            try
            {
                response = UpdateProfileDetails(logobj.Id, logobj.Name, logobj.Emailid, logobj.Mobileno);
            }
            catch
            {
                response = "";
            }
            string Url = string.Empty;
            string Responsetype = response == "" ? "Fail" : "Success";

            return Json(new { Responsetype = Responsetype }, JsonRequestBehavior.AllowGet);
        }

        public string UpdateProfileDetails(string id, string name, string emailid, string mobileno)
        {
            string Response = string.Empty;
            try
            {
                using (SqlCommand cmd = new SqlCommand("Proc_SuperAdminLogin"))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@PARA", "UPDATEPROFILEDETAILS");
                    cmd.Parameters.AddWithValue("@NAME", name);
                    cmd.Parameters.AddWithValue("@EMAILID", emailid);
                    cmd.Parameters.AddWithValue("@MOBILENO", mobileno);
                    cmd.Parameters.AddWithValue("@ID", id);
                    if (util.Execute(cmd))
                    {
                        Response = "success";
                    }
                    else
                    {
                        Response = "";
                    }
                }
            }
            catch
            {

                Response = "";
            }
            return Response;
        }


        public ActionResult ChangePassword()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ChangePassword(Login obj)
        {
            using (SqlCommand cmd = new SqlCommand("Proc_SuperAdminLogin"))
            {
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@PARA", "CHANGE_PASSWORD");
                cmd.Parameters.AddWithValue("@USERNAME", Request.Cookies["SuperAdminusername"].Value);
                cmd.Parameters.AddWithValue("@PASSWORD", obj.OldPassword);
                cmd.Parameters.AddWithValue("@NEWPASSWORD", obj.Password);
                DataTable dt = new DataTable();
                dt = util.Display(cmd);
                if (dt.Rows[0]["update"].ToString() == "correct")
                {
                    ViewBag.message = "Success";
                    ViewBag.message1 = "Your Password has been changed Successfully!";
                }
                else
                {
                    ViewBag.message = "fail";
                    ViewBag.message1 = "Sorry ! Password Could not be changed Successfully!";
                }
                ModelState.Clear(); //make blank to class property
            }
            return View();
        }

        #endregion xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx--- Billing Profile Section End---xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


        #region xxxxxxxxxxxxxxxxxxxxxxxxx--- Add Category ---xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 

        public ActionResult Category()
        {
            Category objauction = new Category();
            objauction.GridList = GetcategoryList();
            return View(objauction);
        }

        public List<Category> GetcategoryList()
        {
            try
            {
                List<Category> objAuctionlist = new List<Category>();
                DataTable dt = new DataTable();
                dt = util.Display("Execute spGetcategory");
                if (dt.Rows.Count > 0)
                {
                    foreach (DataRow dr in dt.Rows)
                    {
                        Category objauc = new Category();
                        objauc.Sr = dr["Sr"].ToString();
                        objauc.categoryid = int.Parse(dr["categoryid"].ToString());
                        objauc.category = dr["Category"].ToString();


                        objAuctionlist.Add(objauc);
                    }
                }
                return objAuctionlist;
            }
            catch (Exception ex)
            {
                LogError log = new LogError();
                log.HandleException(ex);

                ViewBag.Message = "error";
                ViewBag.Message1 = "Try again after some time.";

                TempData["Message"] = ViewBag.Message;
                TempData["Message1"] = ViewBag.Message1;

                return null;
            }
        }



        [HttpPost]
        //[ValidateInput(false)]
        public ActionResult Category(Category auc)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (auc.categoryid == 0)
                    {
                        if (Savecategory(auc))
                        {
                            ModelState.Clear();
                            ViewBag.Message = "success";
                            ViewBag.Message1 = "Category added successfully.";

                            TempData["Message"] = ViewBag.Message;
                            TempData["Message1"] = ViewBag.Message1;

                            return RedirectToAction("Category");
                        }
                        else
                        {
                            ViewBag.Message = "warning";
                            ViewBag.Message1 = "Category could not added successfully.";

                            TempData["Message"] = ViewBag.Message;
                            TempData["Message1"] = ViewBag.Message1;

                            return RedirectToAction("Category");
                        }
                    }
                    else
                    {
                        if (Updatecategory(auc))
                        {
                            ViewBag.Message = "success";
                            ViewBag.Message1 = "Category updated successfully.";

                            TempData["Message"] = ViewBag.Message;
                            TempData["Message1"] = ViewBag.Message1;

                            return RedirectToAction("Category");
                        }
                        else
                        {
                            ViewBag.Message = "warning";

astaguru/Astaguru/Controllers/ArtistController.cs
using Astaguru.Models;
using Astaguru.Services.UserService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Astaguru.Controllers
{
    public class ArtistController : Controller
    {
        Auction AUC = new Auction();
        ArtistService AS = new ArtistService();
        //
        // GET: /Artist/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult artistProfile(int artistid)
        {
            AUC = AS.getArtistProfile(artistid);
            return View("~/Views/User/artistProfile.cshtml", AUC);
        }

        [HttpPost]
        public JsonResult AutoArtist(string Prefix)
        {
            Prefix = System.Threading.Thread.CurrentThread.CurrentCulture.TextInfo.ToTitleCase(Prefix.ToLower());
            Auction Obj = new Auction();

            //Note : you can bind same list from database  
            List<Auction> ObjList = AS.getArtistList(); //  new List<Register>()  


            //    //Searching records from list using LINQ query  
            var ArtistName = (from N in ObjList
                              where N.name.Contains(Prefix)
                              select new { N.artistid, N.name });

            if (!ArtistName.Any())
            {
                return Json(new { Status = "Failed" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(ArtistName, JsonRequestBehavior.AllowGet);
            }
        }

	}
}

astaguru/Astaguru/Views/AdminCms/Artist.cshtml
@model Astaguru.Models.AdminCms.Artist
@using System.Web.Optimization

@{
    ViewBag.Title = "Admin || Artist";
    Layout = "~/Views/Shared/AdminMaster.cshtml";
}

<div class="right_col" role="main">
    <div class="">
        <div class="clearfix"></div>

        @using (Html.BeginForm("Artist", "AdminCms", FormMethod.Post, new { @enctype = "multipart/form-data" }))
        {
            <div class="row">
                @*<div class="col-md-9 col-sm-12 col-xs-12 col-md-offset-1">*@
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Artist</h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            @if (TempData["Message"] != null)
                            {
                                if (TempData["Message"].ToString() == "success")
                                {
                                    <div class="alert alert-success alert-dismissible fade in" role="alert">
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">×</span>
                                        </button>
                                        @TempData["Message1"].ToString()
                                    </div>
                                }

                                else if (TempData["Message"].ToString() == "warning")
                                {
                                    <div class="alert alert-warning alert-dismissible fade in" role="alert">
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">×</span>
                                        </button>
                                        @TempData["Message1"].ToString()
                                    </div>
                                }
                                else if (TempData["Message"].ToString() == "error")
                                {
                                    <div class="alert alert-danger alert-dismissible fade in" role="alert">
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">×</span>
                                        </button>
                                        @TempData["Message1"].ToString()
                                    </div>
                                }
                            }

                            <br>
                            <div id="demo-form2" data-parsley-validate="" class="form-horizontal form-label-left" novalidate="">

                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">
                                        First Name <span class="required" style="color:red">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        @Html.TextBoxFor(m => m.firstname, new { @class = "form-control col-md-7 col-xs-12", @id = "txtFirstName", @autocomplete = "off" })
                                        @Html.ValidationMessageFor(m => m.firstname, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">
                                        Last Name <span class="required" style="color:red">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        @Html.TextBoxFor(m => m.lastname, new { @class = "form-control col-md-7 col-xs-12", @id = "txtLastName", @autocomplete = "off" })
                                        @Html.ValidationMessageFor(m => m.lastname, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">
                                        Profile <span class="required" style="color:red">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        @Html.TextAreaFor(m => m.Profile, new { @class = "form-control col-md-7 col-xs-12", @id = "txtProfile", @autocomplete = "off" })
                                        @Html.ValidationMessageFor(m => m.Profile, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">
                                        Picture <span class="required" style="color:red">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        @Html.TextBoxFor(m => m.Picture, new { @class = "form-control col-md-7 col-xs-12", @id = "fileUploadImage", @autocomplete = "off", @type = "file" })
                                        @Html.ValidationMessageFor(m => m.Picture, "", new { @class = "text-danger" })
                                        <img id="imgPreview" style="display:none;height:100px;width:150px;" />
                                    </div>
                                </div>

                                <div class="ln_solid"></div>

                                <div class="form-group">
                                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                        @if (ViewBag.ActionType == "Update")
                                        {
                                            <input type="submit" value="Update" id="btnsumbit" class="btn btn-success StoreDDLValueinhihhenfields" title="Submit" name="btnAction">
                                            @Html.HiddenFor(m => m.artistid, new { id = "artistid" })
                                            @Html.HiddenFor(m => m.imgPreview, new { @id = "hdnImage" })

                                        }
                                        else
                                        {
                                            <input type="submit" value="Submit" id="btnsumbit" class="btn btn-success StoreDDLValueinhihhenfields" title="Submit" name="btnAction">
                                        }

                                        <input type="reset" value="Cancel" id="btnreset" class="btn btn-primary" title="Cancel">
                                        @*<input type="button" value="View List" title="View List" class="btn btn-dark" id="btnviewlist">*@
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }

        <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Sr No.</th>

                                    <th>
                                        First Name
                                    </th>
                                    <th>
                                        Last Name
                                    </th>
                                    <th>
                                        Profile
                                    </th>
                                    <th>
                                        Picture
                                    </th>

                                    <th>Action</th>
                                </tr>
                            </thead>

                            <tbody>

                                @if (Model.GridList != null)
                                {
                                    foreach (var item in Model.GridList)
                                    {
                                        <tr class="counter">
                                            <td>@Html.DisplayFor(modelItem => item.Sr)</td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.firstname)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.lastname)
                                            </td>
                                            <td>
                                                @*@Html.DisplayFor(modelItem => item.Profile)*@
                                                @Html.Raw(item.Profile)
                                            </td>
                                            <td>
                                                @*@Html.DisplayFor(modelItem => item.Picture)*@
                                                <img src="~/@item.Picture" style="height:100px;width:150px;" />
                                            </td>
                                            <td>
                                                <a href="@Url.Action("EditArtist", "AdminCms", new { id = item.artistid})" title="Edit">
                                                    <button type="button" class="btn ">
                                                        <i class="fa fa-edit"></i>
                                                    </button>
                                                </a>
                                               
                                                <a href="@Url.Action("DeleteArtist", "AdminCms", new { id = item.artistid })" title="Delete" onclick="return confirm('Are you sure you want to delete this Record?')">
                                                        <button type="button" class="btn ">
                                                            <i class="fa fa-close"></i>
                                                        </button>
                                                    </a>

                                            </td>
                                        </tr>
                                    }
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

@Scripts.Render("~/Admin/FormValidation")
<script src="~/Content/Admin/ckeditor/ckeditor.js?@DateTime.Now.Millisecond"></script>
<script type="text/javascript" src="~/Content/Admin/ckeditor/adapters/jquery.js"></script>


<script type="text/javascript">

    $(function () {
        CKEDITOR.replace("txtProfile"); 
    });



    var id = $("#artistid").val();
    //alert(id)
    if (id != undefined && id != 0) {
        $('#imgPreview').show();
        $('#imgPreview').attr('src','/'+ $("#hdnImage").val());
    }

    $('.StoreDDLValueinhihhenfields').click(function () {
        var imgVal = $("#hdnImage").val();
        if (imgVal != undefined && imgVal != "") {
            $('#fileUploadImage').rules('remove', 'required')
        }
    })
</script>





